### ISSUE TITLE
Tray does not show up for players when using "Ready Set Roll"

### ISSUE THREAD

**Issue by nschoenwald** [etiquettestartshere/effectivetray#75]
The module works perfectly on the GM side while also using Ready Set Roll, but unfortunately, the tray does not show up for players. Could this incompatibility be fixed? It would be great.

**Comment by etiquettestartshere** [comment]
which tray?

**Comment by etiquettestartshere** [comment]
can you describe, in detail, what functionality of the module you are after, and what compatibility you want, for players specifically?

**Comment by etiquettestartshere** [comment]
at this point im going to say no, i have no interest in supporting modules i dont use, and the only reason it isnt working as intended, as far as i can tell, is that rsr removes flags from system produced chat cards. if someone wants to make a PR for this kind of compatibility that doesnt increase complexity, i'll consider it, but supporting this kind of compatibility over multiple versions stresses me out.
