### ISSUE TITLE
MidiQoL Incompatibility

### ISSUE THREAD

**Issue by Tosh0kan** [etiquettestartshere/effectivetray#88]
There is some issue that this mod has where the damage calculation is wildly off if Midi is active. For example, I rolled a damage of 9, but in the tray, it wants to apply 18 (target does not have weakness against damage type). Do you know what could be happening?

**Comment by etiquettestartshere** [comment]
i have no plans to support midi-qol. if you can replicate the bug without midi-qol, please reopen the issue.
